db0:
  image: mysql
  ports:
   - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
db1:
  image: mysql
  ports:
   - "3307:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
db2:
  image: mysql
  ports:
   - "3308:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
db3:
  image: mysql
  ports:
   - "3309:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123456